#define MAX_STARCLAN_FAVOR 1000

#define STARCLAN_FAVOR_GOOD 800
#define STARCLAN_FAVOR_WAVERING 600
#define STARCLAN_FAVOR_DISFAVORED 400
#define STARCLAN_FAVOR_CURSED 200
#define STARCLAN_FAVOR_ABANDONED 0

#define CLAN_TYPE_MODERN "modern"
#define CLAN_TYPE_SETTLER "settler"
